// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQv2hWpoPJDa6UAl3M4crJ7VPZhl9mIG8',
    appId: '1:754204378673:web:5d1bb52b9ff280a80e7710',
    messagingSenderId: '754204378673',
    projectId: 'glow-application-6f1d1',
    authDomain: 'glow-application-6f1d1.firebaseapp.com',
    storageBucket: 'glow-application-6f1d1.firebasestorage.app',
    measurementId: 'G-EQW5SVKVXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiJ-db9V72Xb9Uymu3Wlwqq3JVLpzJXAk',
    appId: '1:754204378673:android:afcd7a2aae5b90330e7710',
    messagingSenderId: '754204378673',
    projectId: 'glow-application-6f1d1',
    storageBucket: 'glow-application-6f1d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq0evIX4mt3BYgE3Rsff6yxC19oNDyo0A',
    appId: '1:754204378673:ios:68cd4f8ae3ccb91e0e7710',
    messagingSenderId: '754204378673',
    projectId: 'glow-application-6f1d1',
    storageBucket: 'glow-application-6f1d1.firebasestorage.app',
    iosBundleId: 'com.example.glowApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq0evIX4mt3BYgE3Rsff6yxC19oNDyo0A',
    appId: '1:754204378673:ios:68cd4f8ae3ccb91e0e7710',
    messagingSenderId: '754204378673',
    projectId: 'glow-application-6f1d1',
    storageBucket: 'glow-application-6f1d1.firebasestorage.app',
    iosBundleId: 'com.example.glowApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQv2hWpoPJDa6UAl3M4crJ7VPZhl9mIG8',
    appId: '1:754204378673:web:2a5248b89eeaf0bc0e7710',
    messagingSenderId: '754204378673',
    projectId: 'glow-application-6f1d1',
    authDomain: 'glow-application-6f1d1.firebaseapp.com',
    storageBucket: 'glow-application-6f1d1.firebasestorage.app',
    measurementId: 'G-VRDNMW9SV1',
  );
}
